# Generated by Django 6.0 on 2026-01-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_image_1',
            field=models.ImageField(blank=True, help_text='Optional item image 1', null=True, upload_to='products/items/'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_image_2',
            field=models.ImageField(blank=True, help_text='Optional item image 2', null=True, upload_to='products/items/'),
        ),
    ]
