# Generated by Django 6.0 on 2026-01-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_product_item_image_1_product_item_image_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
